### ISSUE TITLE
What about slow uncached random get latency

### ISSUE THREAD

**Issue by ddorian** [danthegoodman1/ObjectKV#7]

**Comment by danthegoodman1** [comment]
Not sure what specifically you're asking, but if it's what the performance is: I don't know yet, I've only just started hacking on this, segment writing isn't even done yet.

It's likely going to be in the 100-200ms range depending on which S3 compatible storage you use.

For example if you use s3 express it will likely be <20ms.

Certainly slower than a cached segment.

**Comment by ddorian** [comment]
Was curious how you've thought of handling it.
Keep in mind also on node failover. You will have a lot more of slow gets.
Imagine scenario where you have 3 nodes, each with nice local cache, and you lose 1 of them.

**Comment by danthegoodman1** [comment]
I don’t plan on native support for multiple nodes sharing one key space, that would complicate the package with consensus for consistent operations when that’s something that can be implemented on top of the package. A dev can coordinate with etcd, likely better to have fast failover than consensus in this case.
